# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/order.proto for package 'leo'

require 'grpc'
require 'proto/order_pb'

module Leo
  module OrderService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'leo.OrderService'

      rpc :PostOrder, ::Leo::PostOrderRequest, ::Leo::PostOrderResponse
      rpc :ListOrderByProductId, ::Leo::ListOrderByProductIdRequest, ::Leo::ListOrderByProductIdResponse
      rpc :ListOrderByOrdererId, ::Leo::ListOrderByOrdererIdRequest, ::Leo::ListOrderByOrdererIdResponse
      rpc :FindOrder, ::Leo::FindOrderRequest, ::Leo::FindOrderResponse
      rpc :DeleteOrder, ::Leo::DeleteOrderRequest, ::Leo::DeleteOrderResponse
    end

    Stub = Service.rpc_stub_class
  end
end
