# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/order.proto for package 'cancer'

require 'grpc'
require 'proto/order_pb'

module Cancer
  module OrderService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'cancer.OrderService'

      rpc :PostOrder, ::Cancer::PostOrderRequest, ::Cancer::PostOrderResponse
      rpc :ListOrderBySellerId, ::Cancer::ListOrderBySellerIdRequest, ::Cancer::ListOrderBySellerIdResponse
      rpc :ListOrderByOrdererId, ::Cancer::ListOrderByOrdererIdRequest, ::Cancer::ListOrderByOrdererIdResponse
      rpc :FindOrder, ::Cancer::FindOrderRequest, ::Cancer::FindOrderResponse
      rpc :DeleteOrder, ::Cancer::DeleteOrderRequest, ::Cancer::DeleteOrderResponse
    end

    Stub = Service.rpc_stub_class
  end
end
