# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/order.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/order.proto", :syntax => :proto3) do
    add_message "cancer.Order" do
      optional :id, :string, 1
      optional :productId, :string, 2
      optional :ordererId, :string, 3
      optional :sellerId, :string, 4
      optional :price, :int64, 5
      optional :productName, :string, 6
      optional :ordererName, :string, 7
      optional :sellerName, :string, 8
      optional :createdAt, :int64, 9
    end
    add_message "cancer.PostOrderRequest" do
      optional :productId, :string, 1
      optional :ordererId, :string, 2
    end
    add_message "cancer.ListOrderBySellerIdRequest" do
      optional :sellerId, :string, 1
    end
    add_message "cancer.ListOrderByOrdererIdRequest" do
      optional :ordererId, :string, 1
    end
    add_message "cancer.FindOrderRequest" do
      optional :id, :string, 1
    end
    add_message "cancer.DeleteOrderRequest" do
      optional :id, :string, 1
    end
    add_message "cancer.PostOrderResponse" do
      optional :order, :message, 1, "cancer.Order"
    end
    add_message "cancer.ListOrderBySellerIdResponse" do
      repeated :orders, :message, 1, "cancer.Order"
    end
    add_message "cancer.ListOrderByOrdererIdResponse" do
      repeated :orders, :message, 1, "cancer.Order"
    end
    add_message "cancer.FindOrderResponse" do
      optional :order, :message, 1, "cancer.Order"
    end
    add_message "cancer.DeleteOrderResponse" do
    end
  end
end

module Cancer
  Order = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cancer.Order").msgclass
  PostOrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cancer.PostOrderRequest").msgclass
  ListOrderBySellerIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cancer.ListOrderBySellerIdRequest").msgclass
  ListOrderByOrdererIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cancer.ListOrderByOrdererIdRequest").msgclass
  FindOrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cancer.FindOrderRequest").msgclass
  DeleteOrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cancer.DeleteOrderRequest").msgclass
  PostOrderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cancer.PostOrderResponse").msgclass
  ListOrderBySellerIdResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cancer.ListOrderBySellerIdResponse").msgclass
  ListOrderByOrdererIdResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cancer.ListOrderByOrdererIdResponse").msgclass
  FindOrderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cancer.FindOrderResponse").msgclass
  DeleteOrderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cancer.DeleteOrderResponse").msgclass
end
