# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/product.proto for package 'leo'

require 'grpc'
require 'proto/product_pb'

module Leo
  module ProductService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'leo.ProductService'

      rpc :PostProduct, ::Leo::PostProductRequest, ::Leo::PostProductResponse
      rpc :ListProduct, ::Leo::ListProductRequest, ::Leo::ListProductResponse
      rpc :ListProductBySellerId, ::Leo::ListProductBySellerIdRequest, ::Leo::ListProductBySellerIdResponse
      rpc :FindProduct, ::Leo::FindProductRequest, ::Leo::FindProductResponse
      rpc :UpdateProduct, ::Leo::UpdateProductRequest, ::Leo::UpdateProductResponse
      rpc :DeleteProduct, ::Leo::DeleteProductRequest, ::Leo::DeleteProductResponse
    end

    Stub = Service.rpc_stub_class
  end
end
