# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/user.proto", :syntax => :proto3) do
    add_message "leo.User" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :email, :string, 3
      optional :createdAt, :int64, 4
      oneof :updatedAtOneof do
        optional :updatedAt, :int64, 5
      end
    end
    add_message "leo.PostUserRequest" do
      optional :name, :string, 1
      optional :email, :string, 2
      optional :password, :string, 3
    end
    add_message "leo.ListUserRequest" do
    end
    add_message "leo.FindUserRequest" do
      optional :id, :string, 1
    end
    add_message "leo.UpdateUserRequest" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :email, :string, 3
      optional :password, :string, 4
    end
    add_message "leo.DeleteUserRequest" do
      optional :id, :string, 1
    end
    add_message "leo.PostUserResponse" do
      optional :user, :message, 1, "leo.User"
    end
    add_message "leo.ListUserResponse" do
      repeated :users, :message, 1, "leo.User"
    end
    add_message "leo.FindUserResponse" do
      optional :user, :message, 1, "leo.User"
    end
    add_message "leo.UpdateUserResponse" do
      optional :user, :message, 1, "leo.User"
    end
    add_message "leo.DeleteUserResponse" do
    end
  end
end

module Leo
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("leo.User").msgclass
  PostUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("leo.PostUserRequest").msgclass
  ListUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("leo.ListUserRequest").msgclass
  FindUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("leo.FindUserRequest").msgclass
  UpdateUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("leo.UpdateUserRequest").msgclass
  DeleteUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("leo.DeleteUserRequest").msgclass
  PostUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("leo.PostUserResponse").msgclass
  ListUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("leo.ListUserResponse").msgclass
  FindUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("leo.FindUserResponse").msgclass
  UpdateUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("leo.UpdateUserResponse").msgclass
  DeleteUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("leo.DeleteUserResponse").msgclass
end
